username=input("Enter the user name: ")
Age=input("Enter the user's age: ")
print("Enter the user name and age: "+username+","+Age)
Year=2023+(100-int(Age))
print("Year in which"+username+"will become 100 is: "+str(Year))